"""change discord_channel_id

Revision ID: 0002
Revises: 0001_initial
Create Date: 2025-10-23 22:41:38.738775

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "channel_dynamic",
        "discord_channel_id",
        existing_type=sa.String(length=64),
        type_=sa.BigInteger(),
        postgresql_using="discord_channel_id::bigint",
        existing_nullable=False,
    )
    op.alter_column(
        "channel_static",
        "discord_channel_id",
        existing_type=sa.String(length=64),
        type_=sa.BigInteger(),
        postgresql_using="discord_channel_id::bigint",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "channel_static",
        "discord_channel_id",
        existing_type=sa.BigInteger(),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "channel_dynamic",
        "discord_channel_id",
        existing_type=sa.BigInteger(),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
