"""rename discord_channel_id and add two columns

Revision ID: 0003
Revises: 0002
Create Date: 2025-10-23 22:44:41.387877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "channel_dynamic", "discord_channel_id", new_column_name="channel_id"
    )
    op.add_column(
        "channel_dynamic",
        sa.Column("name", sa.String(length=100), nullable=False, server_default="None"),
    )
    op.add_column(
        "channel_dynamic",
        sa.Column("guild_id", sa.BigInteger(), nullable=False, server_default="-1"),
    )
    op.alter_column("channel_dynamic", "name", server_default=None)
    op.alter_column("channel_dynamic", "guild_id", server_default=None)
    op.alter_column(
        "channel_static", "discord_channel_id", new_column_name="channel_id"
    )
    op.add_column(
        "channel_static",
        sa.Column("name", sa.String(length=100), nullable=False, server_default="None"),
    )
    op.add_column(
        "channel_static",
        sa.Column("guild_id", sa.BigInteger(), nullable=False, server_default="-1"),
    )
    op.alter_column("channel_static", "name", server_default=None)
    op.alter_column("channel_static", "guild_id", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "channel_static", "channel_id", new_column_name="discord_channel_id"
    )
    op.drop_column("channel_static", "guild_id")
    op.drop_column("channel_static", "name")
    op.alter_column(
        "channel_dynamic", "channel_id", new_column_name="discord_channel_id"
    )
    op.drop_column("channel_dynamic", "guild_id")
    op.drop_column("channel_dynamic", "name")
    # ### end Alembic commands ###
